# Generated by Django 3.2.9 on 2021-12-15 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_auto_20211215_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineAddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed')]),
        ),
    ]
